version: '3.8'  # Mise à jour pour utiliser une version plus récente de Docker Compose

services:
  ville_api:
    container_name: api
    image: villeapi:1.0
    ports:
      - "${API_PORT}:5532"  # Assurez-vous que le port 5532 est celui que votre application Node.js écoute
    depends_on:
      - ville_db  # Utilisez le nom du service tel que défini dans ce fichier, pas le nom du conteneur
    working_dir: /app
    volumes:
      - ./volumes/app/${VILLE}:/app
    stdin_open: true
    tty: true
    networks:
      - Devreos

  ville_db:
    container_name: ${VILLE}_db
    image: postgres:15-alpine
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ./volumes/data/${VILLE}:/var/lib/postgresql/data  # Correction du chemin pour utiliser un chemin relatif
      - ./volumes/data/init/:/docker-entrypoint-initdb.d/  # Correction du chemin pour utiliser un chemin relatif
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${VILLE}
      POSTGRES_USER: ${DB_USER}  # Ajout de la variable d'environnement pour l'utilisateur de la DB
    networks:
      - Devreos

networks:
  Devreos:
    external: true
