version: '2'
services:
  api:
    container_name: api
    image: node:18-alpine
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    working_dir: /app
    volumes:
      - ./:/app
    stdin_open: true 
    tty: true
    networks:
      - knoss 

  db:
    container_name: postgres
    image: postgres:15-alpine
    ports:
      - '${DB_HOST_PORT}:${DB_PORT}'
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - knoss

  db_odoo:
    container_name: db_odoo
    image: postgres:15-alpine
    user: root
    ports:
      - '5432:5432'
    volumes:
        - ./postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${ODOO_DB_USER}    # Doit être 'odoo' si vous suivez la configuration d'Odoo
      - POSTGRES_PASSWORD=${ODOO_DB_PASSWORD} # Doit correspondre au mot de passe défini dans le service Odoo
      - POSTGRES_DB=db_odoo
    networks:
      - knoss

volumes:
  data:

networks:
  knoss:
    external: true